### ISSUE TITLE
doesn't mute when streaming to chromecast device

### ISSUE THREAD

**Issue by tomerrr** [imkival/spotblock-rs#2]
even though the notification for the track was "advertisement" , spotblock didn't mute any sink when i was using Spotify's "connect to device" option, to stream to Google Chromcast device group.
I believe the issue is related to Spotify streaming directly to Chromecast devices without creating new sinks in pulseaudio.

**Comment by imkival** [comment]
I do not think this will be possible to implement since (as far as i know) the music is not streaming from your PC to the Chrome-cast, but instead your PC is telling the Chrome-cast what to play from spotify. The audio never passes through your device

Your PC is not the device playing the music, so unless you could find a way of installing the program on a chrome-cast this will not be possible.

However, If you have a router that supports blocking certain domains, you can set it up in such a way that spotify will fail to load ads
[https://wiki.archlinux.org/title/Spotify#Hosts_file](https://wiki.archlinux.org/title/Spotify#Hosts_file)

**Comment by tomerrr** [comment]
ok, that totally makes sense. going to use Pulseaudio-DLNA as a workaround, as it creates virtual sound cards for any CC device.
I don't think DNS ad blocking is working anymore with Spotify
